Ruadrect
natasha/corus pull request #52
Opened 2020-10-26 17:45 UTC by Ilseyar

Added RuADReCT corpus from Toloka

2020-10-26 18:03 UTC, kuk requested changes
В целом, все хорошо, посмотрите, пожалуйста, комментарии по деталям.

2020-10-26 18:03 UTC, kuk commented on .idea/.gitignore
> +
Директорию .idea лучше убрать. Можно добавить в .gitignore. Кто-то использует эту IDE, кто-то нет. Я, например, не использую, зачем мне эти файлы.

2020-10-26 18:03 UTC, kuk commented on corus/sources/toloka.py
> +def load_lines_ruadrect(path):
Вроде бы, это то же самое что load_lines из https://github.com/natasha/corus/blob/master/corus/io.py#L49? Есть какой-то особый смысл явно указывать encoding?

2020-10-26 18:03 UTC, kuk commented on data/toloka/ruadrect/task2_ru_test.tsv
> +tweet_id	tweet	label
Они одинаковые по формату, может быть, оставить только task2_ru_test.tsv?

2020-10-30 11:42 UTC, Ilseyar commented on corus/sources/toloka.py
> +def load_lines_ruadrect(path):
Если не указывать явно кодировку, то в Windows выводит "каракули" вместо текста. Как оказалось, это связано не только конкретно с корпусом RuADReCT, но и с остальными, которые используют метод load_lines.

2020-10-30 12:50 UTC, kuk commented on corus/sources/toloka.py
> +def load_lines_ruadrect(path):
Вы на Windows? Давайте тогда добавим encoding=utf8 дефолтным параметром прямо в load_lines

2020-10-30 13:52 UTC, Ilseyar commented on corus/sources/toloka.py
> +def load_lines_ruadrect(path):
Да, так получилось, что я на Windows. Хорошо, добавлю тогда дефолтный параметр в исходный метод.

2020-11-09 07:53 UTC, merged

2020-11-09 07:53 UTC, kuk commented
Спасибо!